/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppProgressRouteImport } from './routes/_app/progress'
import { Route as AppScheduleRouteImport } from './routes/_app/schedule'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppGroupsIndexRouteImport } from './routes/_app/groups/index'
import { Route as AppGroupsGroupIdRouteImport } from './routes/_app/groups/$groupId'
import { Route as AppRoomsIndexRouteImport } from './routes/_app/rooms/index'
import { Route as AppTasksIndexRouteImport } from './routes/_app/tasks/index'
import { Route as AppTasksTaskIdRouteImport } from './routes/_app/tasks/$taskId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGroupsIndexRoute = AppGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGroupsGroupIdRoute = AppGroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRoomsIndexRoute = AppRoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTasksIndexRoute = AppTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTasksTaskIdRoute = AppTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/progress': typeof AppProgressRoute
  '/schedule': typeof AppScheduleRoute
  '/settings': typeof AppSettingsRoute
  '/groups/$groupId': typeof AppGroupsGroupIdRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/groups/': typeof AppGroupsIndexRoute
  '/rooms/': typeof AppRoomsIndexRoute
  '/tasks/': typeof AppTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/progress': typeof AppProgressRoute
  '/schedule': typeof AppScheduleRoute
  '/settings': typeof AppSettingsRoute
  '/groups/$groupId': typeof AppGroupsGroupIdRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/groups': typeof AppGroupsIndexRoute
  '/rooms': typeof AppRoomsIndexRoute
  '/tasks': typeof AppTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/progress': typeof AppProgressRoute
  '/_app/schedule': typeof AppScheduleRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/groups/$groupId': typeof AppGroupsGroupIdRoute
  '/_app/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/_app/groups/': typeof AppGroupsIndexRoute
  '/_app/rooms/': typeof AppRoomsIndexRoute
  '/_app/tasks/': typeof AppTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/progress'
    | '/schedule'
    | '/settings'
    | '/groups/$groupId'
    | '/tasks/$taskId'
    | '/groups/'
    | '/rooms/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/progress'
    | '/schedule'
    | '/settings'
    | '/groups/$groupId'
    | '/tasks/$taskId'
    | '/groups'
    | '/rooms'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/progress'
    | '/_app/schedule'
    | '/_app/settings'
    | '/_app/groups/$groupId'
    | '/_app/tasks/$taskId'
    | '/_app/groups/'
    | '/_app/rooms/'
    | '/_app/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/progress': {
      id: '/_app/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/schedule': {
      id: '/_app/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/groups/': {
      id: '/_app/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AppGroupsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/groups/$groupId': {
      id: '/_app/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof AppGroupsGroupIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/rooms/': {
      id: '/_app/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof AppRoomsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tasks/': {
      id: '/_app/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AppTasksIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tasks/$taskId': {
      id: '/_app/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AppTasksTaskIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppProgressRoute: typeof AppProgressRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppGroupsGroupIdRoute: typeof AppGroupsGroupIdRoute
  AppTasksTaskIdRoute: typeof AppTasksTaskIdRoute
  AppGroupsIndexRoute: typeof AppGroupsIndexRoute
  AppRoomsIndexRoute: typeof AppRoomsIndexRoute
  AppTasksIndexRoute: typeof AppTasksIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppProgressRoute: AppProgressRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppGroupsGroupIdRoute: AppGroupsGroupIdRoute,
  AppTasksTaskIdRoute: AppTasksTaskIdRoute,
  AppGroupsIndexRoute: AppGroupsIndexRoute,
  AppRoomsIndexRoute: AppRoomsIndexRoute,
  AppTasksIndexRoute: AppTasksIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
